// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssrdpennlscdaanvfxjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzcmRwZW5ubHNjZGFhbnZmeGpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MzY5MDUsImV4cCI6MjA3MTUxMjkwNX0.wAK1DYI3kIYXVdKww2YDwb8bppAHV8rLrxEh49QdOgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});